In [1]:
import pandas as pd

In [2]:
from google.colab import files
uploaded = files.upload()

Saving 01-31-Jan-2026-Zepto.csv to 01-31-Jan-2026-Zepto.csv
Saving myntra-jan26.csv to myntra-jan26.csv
Saving 1-31-Jan-Nykaa-online.csv to 1-31-Jan-Nykaa-online.csv
Saving 01-31-Jan-2026-Blinkit-Sales.csv to 01-31-Jan-2026-Blinkit-Sales.csv

In [3]:
import pandas as pd

df = pd.read_csv("01-31-Jan-2026-Zepto.csv")

print(df.head())

         Date                            SKU Number  \
0  21-01-2026  e4a7998c-9073-45a0-9d8c-a8747e811f06
1  30-01-2026  07e74fc5-7ecd-43d8-a3a8-6b6cd221026a
2  26-01-2026  e4a7998c-9073-45a0-9d8c-a8747e811f06
3  22-01-2026  07e74fc5-7ecd-43d8-a3a8-6b6cd221026a
4  21-01-2026  07e74fc5-7ecd-43d8-a3a8-6b6cd221026a

                                            SKU Name            EAN  \
0  inde wild Champi Hair Oil With Bhringraj, Brah...  8721008106403
1          inde wild Champi Hair Oil 50.0 MILLILITRE  8721008106175
2  inde wild Champi Hair Oil With Bhringraj, Brah...  8721008106403
3          inde wild Champi Hair Oil 50.0 MILLILITRE  8721008106175
4          inde wild Champi Hair Oil 50.0 MILLILITRE  8721008106175

  SKU Category SKU Sub Category Brand Name          Manufacturer Name  \
0    Hair Care         Hair Oil  inde wild  Inde Wild Private Limited
1    Hair Care         Hair Oil  inde wild  Inde Wild Private Limited
2    Hair Care         Hair Oil  inde wild  Inde Wild Private Limited
3    Hair Care         Hair Oil  inde wild  Inde Wild Private Limited
4    Hair Care         Hair Oil  inde wild  Inde Wild Private Limited

                        Manufacturer ID      City  Sales (Qty) - Units    MRP  \
0  bad850c4-e659-44bf-8d49-cd9e21520f5f    Mumbai                    2  355.0
1  bad850c4-e659-44bf-8d49-cd9e21520f5f    Mumbai                   11  844.0
2  bad850c4-e659-44bf-8d49-cd9e21520f5f    Mumbai                    2  355.0
3  bad850c4-e659-44bf-8d49-cd9e21520f5f    Mumbai                    6  844.0
4  bad850c4-e659-44bf-8d49-cd9e21520f5f  Gurugram                    3  844.0

   Gross Merchandise Value
0                      710
1                     9284
2                      710
3                     5064
4                     2532

In [4]:
df.head(10)

,Date,SKU Number,SKU Name,EAN,SKU Category,SKU Sub Category,Brand Name,Manufacturer Name,Manufacturer ID,City,Sales (Qty) - Units,MRP,Gross Merchandise Value
0,21-01-2026,e4a7998c-9073-45a0-9d8c-a8747e811f06,"inde wild Champi Hair Oil With Bhringraj, Brah...",8721008106403,Hair Care,Hair Oil,inde wild,Inde Wild Private Limited,bad850c4-e659-44bf-8d49-cd9e21520f5f,Mumbai,2,355.0,710
1,30-01-2026,07e74fc5-7ecd-43d8-a3a8-6b6cd221026a,inde wild Champi Hair Oil 50.0 MILLILITRE,8721008106175,Hair Care,Hair Oil,inde wild,Inde Wild Private Limited,bad850c4-e659-44bf-8d49-cd9e21520f5f,Mumbai,11,844.0,9284
2,26-01-2026,e4a7998c-9073-45a0-9d8c-a8747e811f06,"inde wild Champi Hair Oil With Bhringraj, Brah...",8721008106403,Hair Care,Hair Oil,inde wild,Inde Wild Private Limited,bad850c4-e659-44bf-8d49-cd9e21520f5f,Mumbai,2,355.0,710
3,22-01-2026,07e74fc5-7ecd-43d8-a3a8-6b6cd221026a,inde wild Champi Hair Oil 50.0 MILLILITRE,8721008106175,Hair Care,Hair Oil,inde wild,Inde Wild Private Limited,bad850c4-e659-44bf-8d49-cd9e21520f5f,Mumbai,6,844.0,5064
4,21-01-2026,07e74fc5-7ecd-43d8-a3a8-6b6cd221026a,inde wild Champi Hair Oil 50.0 MILLILITRE,8721008106175,Hair Care,Hair Oil,inde wild,Inde Wild Private Limited,bad850c4-e659-44bf-8d49-cd9e21520f5f,Gurugram,3,844.0,2532
5,19-01-2026,3fa4c1a5-3183-4619-8774-491e2fd1008a,inde wild Dewy Lip Treatment 15.0 MILLILITRE,8721008106335,Skincare,Eye & Lip Care,inde wild,Inde Wild Private Limited,bad850c4-e659-44bf-8d49-cd9e21520f5f,Mumbai,4,799.0,3196
6,10-01-2026,32680322-fb74-4724-90e6-5377faa630a3,"inde wild Moonlight Scalp Serum with Moringa, ...",8721008106366,Hair Care,Hair Serum & Polish,inde wild,Inde Wild Private Limited,bad850c4-e659-44bf-8d49-cd9e21520f5f,Bengaluru,4,499.0,1996
7,09-01-2026,3fa4c1a5-3183-4619-8774-491e2fd1008a,inde wild Dewy Lip Treatment 15.0 MILLILITRE,8721008106335,Skincare,Eye & Lip Care,inde wild,Inde Wild Private Limited,bad850c4-e659-44bf-8d49-cd9e21520f5f,Hyderabad,2,799.0,1598
8,30-01-2026,9e7b013e-5aff-4eb6-b474-ac94c392e348,inde wild Rose Sun Mist SPF 50 Pa 60.0 MILLILITRE,8721008106229,Skincare,Sun Care,inde wild,Inde Wild Private Limited,bad850c4-e659-44bf-8d49-cd9e21520f5f,Hyderabad,4,849.0,3396
9,11-01-2026,94930f70-e21f-4103-9bf8-9f3330478fa7,inde wild Moonlight Scalp Serum 50.0 MILLILITRE,8721008106250,Hair Care,Hair Serum & Polish,inde wild,Inde Wild Private Limited,bad850c4-e659-44bf-8d49-cd9e21520f5f,Bengaluru,1,1199.0,1199

In [5]:
df_zepto=df.copy()

In [6]:
df_zepto['date']=pd.to_datetime(df_zepto['Date'], dayfirst=True)

In [7]:
df_zepto['product_identifier'] = df_zepto['SKU Number']
df_zepto['total_units'] = df_zepto['Sales (Qty) - Units']
df_zepto['total_revenue'] = df_zepto['Gross Merchandise Value']

In [8]:
df_zepto['data_source'] = 'Zepto'

In [9]:
df_zepto = df_zepto[['date', 'product_identifier', 'total_units', 'total_revenue', 'data_source']]

In [10]:
df_zepto.head(10)

,date,product_identifier,total_units,total_revenue,data_source
0,2026-01-21,e4a7998c-9073-45a0-9d8c-a8747e811f06,2,710,Zepto
1,2026-01-30,07e74fc5-7ecd-43d8-a3a8-6b6cd221026a,11,9284,Zepto
2,2026-01-26,e4a7998c-9073-45a0-9d8c-a8747e811f06,2,710,Zepto
3,2026-01-22,07e74fc5-7ecd-43d8-a3a8-6b6cd221026a,6,5064,Zepto
4,2026-01-21,07e74fc5-7ecd-43d8-a3a8-6b6cd221026a,3,2532,Zepto
5,2026-01-19,3fa4c1a5-3183-4619-8774-491e2fd1008a,4,3196,Zepto
6,2026-01-10,32680322-fb74-4724-90e6-5377faa630a3,4,1996,Zepto
7,2026-01-09,3fa4c1a5-3183-4619-8774-491e2fd1008a,2,1598,Zepto
8,2026-01-30,9e7b013e-5aff-4eb6-b474-ac94c392e348,4,3396,Zepto
9,2026-01-11,94930f70-e21f-4103-9bf8-9f3330478fa7,1,1199,Zepto

In [11]:
print(df_zepto.isnull().sum())

date                  0
product_identifier    0
total_units           0
total_revenue         0
data_source           0
dtype: int64

In [12]:
print(df_zepto.dtypes)

date                  datetime64[ns]
product_identifier            object
total_units                    int64
total_revenue                  int64
data_source                   object
dtype: object

In [13]:
df_myntra = pd.read_csv("myntra-jan26.csv")

print(df_myntra.head())
print(df_myntra.columns)
print(df_myntra.info())

   order_created_date  style_id  \
0            20260123  36659831
1            20260109  36659831
2            20260102  36659825
3            20260121  36660216
4            20260128  36660215

                                          style_name  business_unit  \
0  inde wild Dewy Lip Treatment 15ml - Caffeine A...  Personal Care
1  inde wild Dewy Lip Treatment 15ml - Caffeine A...  Personal Care
2   inde wild Dewy Lip Treatment 15ml - Wedding Rose  Personal Care
3  inde wild Champi Hair Oil with Bhringraj Brahm...  Personal Care
4  inde wild Champi Hair Oil with Bhringraj Brahm...  Personal Care

  brand_type po_type article_type      brand  gender  sales  mrp_revenue  \
0   External     SOR     Lip Balm  inde wild  Unisex      3       2700.0
1   External     SOR     Lip Balm  inde wild  Unisex      3       2700.0
2   External     SOR     Lip Balm  inde wild  Unisex      4       3600.0
3   External     SOR     Hair Oil  inde wild  Unisex     10       9490.0
4   External     SOR     Hair Oil  inde wild  Unisex     12      21600.0

   vendor_disc
0        539.0
1        539.0
2        180.0
3        664.0
4       1080.0
Index(['order_created_date', 'style_id', 'style_name', 'business_unit',
       'brand_type', 'po_type', 'article_type', 'brand', 'gender', 'sales',
       'mrp_revenue', 'vendor_disc'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 337 entries, 0 to 336
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_created_date  337 non-null    int64
 1   style_id            337 non-null    int64
 2   style_name          337 non-null    object
 3   business_unit       337 non-null    object
 4   brand_type          337 non-null    object
 5   po_type             337 non-null    object
 6   article_type        337 non-null    object
 7   brand               337 non-null    object
 8   gender              337 non-null    object
 9   sales               337 non-null    int64
 10  mrp_revenue         337 non-null    float64
 11  vendor_disc         337 non-null    float64
dtypes: float64(2), int64(3), object(7)
memory usage: 31.7+ KB
None

In [14]:
df_myntra_clean = df_myntra.copy()

# Convert date
df_myntra_clean['date'] = pd.to_datetime(
    df_myntra_clean['order_created_date'],
    format='%Y%m%d',
    errors='coerce'
)

# Standardize columns
df_myntra_clean['product_identifier'] = df_myntra_clean['style_id']

df_myntra_clean['total_units'] = df_myntra_clean['sales']

df_myntra_clean['total_revenue'] = df_myntra_clean['mrp_revenue']

# Add source
df_myntra_clean['data_source'] = 'Myntra'

# Select required columns
df_myntra_clean = df_myntra_clean[
    ['date', 'product_identifier', 'total_units', 'total_revenue', 'data_source']
]

In [15]:
print(df_myntra_clean.head())
print(df_myntra_clean.isnull().sum())
print(df_myntra_clean.dtypes)

        date  product_identifier  total_units  total_revenue data_source
0 2026-01-23            36659831            3         2700.0      Myntra
1 2026-01-09            36659831            3         2700.0      Myntra
2 2026-01-02            36659825            4         3600.0      Myntra
3 2026-01-21            36660216           10         9490.0      Myntra
4 2026-01-28            36660215           12        21600.0      Myntra
date                  0
product_identifier    0
total_units           0
total_revenue         0
data_source           0
dtype: int64
date                  datetime64[ns]
product_identifier             int64
total_units                    int64
total_revenue                float64
data_source                   object
dtype: object

In [16]:
df_nykaa = pd.read_csv("1-31-Jan-Nykaa-online.csv")

print(df_nykaa.head())
print(df_nykaa.columns)
print(df_nykaa.info())

         date  seller_code Display Name Company Name    Seller Type  \
0  2026-01-31         3820    Inde Wild    Inde Wild  Brand Company
1  2026-01-31         3820    Inde Wild    Inde Wild  Brand Company
2  2026-01-31         3820    Inde Wild    Inde Wild  Brand Company
3  2026-01-31         3820    Inde Wild    Inde Wild  Brand Company
4  2026-01-31         3820    Inde Wild    Inde Wild  Brand Company

       brand       SKU Code  \
0  inde wild  INDEW00000011
1  inde wild  INDEW00000003
2  inde wild  INDEW00000044
3  inde wild  INDEW00000023
4  inde wild  INDEW00000049

                                            SKU Name Category L1  \
0  inde wild Champi Hair Oil With Bhringraj, Brah...        Hair
1  inde wild Champi Hair Oil With Bhringraj, Brah...        Hair
2               inde wild Champi Bond Repair Shampoo        Hair
3  inde wild Champi Hair Oil With Bhringraj, Brah...        Hair
4                       inde wild Champi Slick Stick        Hair

    Category L2 Category L3       MRP  Display Price  Selling Price  \
0     Hair Care    Hair Oil  209804.0       167796.0      156905.68
1     Hair Care    Hair Oil  287179.0       243167.8      227916.97
2     Hair Care     Shampoo    1150.0         1093.0        1033.44
3     Hair Care    Hair Oil   33915.0        32215.0       30566.33
4  Hair Styling  Gels Waxes     999.0          949.0         871.75

   Total Qty  Total Orders  Total Customers      Platform
0      118.0           110              109  Nykaa Beauty
1      316.0           311              311  Nykaa Beauty
2        1.0             1                1     Nykaa Man
3       85.0            84               84  Nykaa Beauty
4        1.0             1                1     Nykaa Man
Index(['date', 'seller_code', 'Display Name', 'Company Name', 'Seller Type',
       'brand', 'SKU Code', 'SKU Name', 'Category L1', 'Category L2',
       'Category L3', 'MRP', 'Display Price', 'Selling Price', 'Total Qty',
       'Total Orders', 'Total Customers', 'Platform'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 722 entries, 0 to 721
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             722 non-null    object
 1   seller_code      722 non-null    int64
 2   Display Name     722 non-null    object
 3   Company Name     722 non-null    object
 4   Seller Type      722 non-null    object
 5   brand            722 non-null    object
 6   SKU Code         722 non-null    object
 7   SKU Name         722 non-null    object
 8   Category L1      722 non-null    object
 9   Category L2      722 non-null    object
 10  Category L3      722 non-null    object
 11  MRP              722 non-null    float64
 12  Display Price    722 non-null    float64
 13  Selling Price    722 non-null    float64
 14  Total Qty        722 non-null    float64
 15  Total Orders     722 non-null    int64
 16  Total Customers  722 non-null    int64
 17  Platform         722 non-null    object
dtypes: float64(4), int64(3), object(11)
memory usage: 101.7+ KB
None

In [17]:
df_nykaa_clean = df_nykaa.copy()

# Convert date
df_nykaa_clean['date'] = pd.to_datetime(df_nykaa_clean['date'], errors='coerce')

# Standardize columns
df_nykaa_clean['product_identifier'] = df_nykaa_clean['SKU Code']

df_nykaa_clean['total_units'] = df_nykaa_clean['Total Qty']

# 🔥 Important: Calculate revenue
df_nykaa_clean['total_revenue'] = (
    df_nykaa_clean['Selling Price'] * df_nykaa_clean['Total Qty']
)

# Add source
df_nykaa_clean['data_source'] = 'Nykaa'

# Select required columns
df_nykaa_clean = df_nykaa_clean[
    ['date', 'product_identifier', 'total_units', 'total_revenue', 'data_source']
]

In [18]:
print(df_nykaa_clean.head())
print(df_nykaa_clean.isnull().sum())
print(df_nykaa_clean.dtypes)

        date product_identifier  total_units  total_revenue data_source
0 2026-01-31      INDEW00000011        118.0    18514870.24       Nykaa
1 2026-01-31      INDEW00000003        316.0    72021762.52       Nykaa
2 2026-01-31      INDEW00000044          1.0        1033.44       Nykaa
3 2026-01-31      INDEW00000023         85.0     2598138.05       Nykaa
4 2026-01-31      INDEW00000049          1.0         871.75       Nykaa
date                  0
product_identifier    0
total_units           0
total_revenue         0
data_source           0
dtype: int64
date                  datetime64[ns]
product_identifier            object
total_units                  float64
total_revenue                float64
data_source                   object
dtype: object

In [19]:
df_blinkit = pd.read_csv("01-31-Jan-2026-Blinkit-Sales.csv")

print(df_blinkit.head())
print(df_blinkit.columns)
print(df_blinkit.info())

    item_id                                          item_name  \
0  10197348  Inde Wild Dewy Lip Balm Treatment (Glazed Jale...
1  10277303      Inde Wild Champi Bond Repair Conditioner(Box)
2  10277303      Inde Wild Champi Bond Repair Conditioner(Box)
3  10277303      Inde Wild Champi Bond Repair Conditioner(Box)
4  10277303      Inde Wild Champi Bond Repair Conditioner(Box)

   manufacturer_id          manufacturer_name  city_id  city_name  \
0             4722  Inde Wild Private Limited        4    Chennai
1             4722  Inde Wild Private Limited       15    Kolkata
2             4722  Inde Wild Private Limited      205      Hisar
3             4722  Inde Wild Private Limited        1  Bengaluru
4             4722  Inde Wild Private Limited        2     Mumbai

             category        date  qty_sold     mrp
0  Beauty & Cosmetics  2026-01-04       1.0   899.0
1       Personal Care  2026-01-16       2.0  2300.0
2       Personal Care  2026-01-21       1.0  1150.0
3       Personal Care  2026-01-23       1.0  1150.0
4       Personal Care  2026-01-30       3.0  3450.0
Index(['item_id', 'item_name', 'manufacturer_id', 'manufacturer_name',
       'city_id', 'city_name', 'category', 'date', 'qty_sold', 'mrp'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3432 entries, 0 to 3431
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   item_id            3432 non-null   int64
 1   item_name          3432 non-null   object
 2   manufacturer_id    3432 non-null   int64
 3   manufacturer_name  3432 non-null   object
 4   city_id            3432 non-null   int64
 5   city_name          3432 non-null   object
 6   category           3432 non-null   object
 7   date               3432 non-null   object
 8   qty_sold           3432 non-null   float64
 9   mrp                3432 non-null   float64
dtypes: float64(2), int64(3), object(5)
memory usage: 268.3+ KB
None

In [20]:
df_blinkit_clean = df_blinkit.copy()

# Convert date
df_blinkit_clean['date'] = pd.to_datetime(df_blinkit_clean['date'], errors='coerce')

# Standardize columns
df_blinkit_clean['product_identifier'] = df_blinkit_clean['item_id']

df_blinkit_clean['total_units'] = df_blinkit_clean['qty_sold']

df_blinkit_clean['total_revenue'] = df_blinkit_clean['mrp']

# Add source
df_blinkit_clean['data_source'] = 'Blinkit'

# Select required columns
df_blinkit_clean = df_blinkit_clean[
    ['date', 'product_identifier', 'total_units', 'total_revenue', 'data_source']
]

In [21]:
print(df_blinkit_clean.head())
print(df_blinkit_clean.isnull().sum())
print(df_blinkit_clean.dtypes)

        date  product_identifier  total_units  total_revenue data_source
0 2026-01-04            10197348          1.0          899.0     Blinkit
1 2026-01-16            10277303          2.0         2300.0     Blinkit
2 2026-01-21            10277303          1.0         1150.0     Blinkit
3 2026-01-23            10277303          1.0         1150.0     Blinkit
4 2026-01-30            10277303          3.0         3450.0     Blinkit
date                  0
product_identifier    0
total_units           0
total_revenue         0
data_source           0
dtype: int64
date                  datetime64[ns]
product_identifier             int64
total_units                  float64
total_revenue                float64
data_source                   object
dtype: object

In [22]:
final_df = pd.concat([
    df_zepto,
    df_myntra_clean,
    df_nykaa_clean,
    df_blinkit_clean
])

In [23]:
final_df = final_df.groupby(
    ['date', 'product_identifier', 'data_source']
).agg({
    'total_units': 'sum',
    'total_revenue': 'sum'
}).reset_index()

In [26]:
final_df.rename(columns={
    'product_identifier': 'product_identifier(sku)'
}, inplace=True)

In [27]:
final_df = final_df[
    ['date', 'product_identifier(sku)', 'total_units', 'total_revenue', 'data_source']
]

In [28]:
final_df.to_csv("final_sales.csv", index=False)

In [29]:
from google.colab import files
files.download("final_sales.csv")